forestryio/forestry.io

hugo/content/blog/hugo-and-jekyll-compared.md

Going live with the Hugo & Jekyll article

Blogpost hugo jekyll compared

---

hugo/content/blog/build-a-json-api-with-hugo.md

And thanks for this great article!

Typo: « cusotm » -> « custom »

---

hugo/content/docs/troubleshooting/cant-publish-preview-or-save.md

Typo fix: "Site Acvity" to "Site Activity"

---

hugo/content/_index.md
hugo/layouts/index.html
hugo/layouts/partials/components/hero.html

Hey guys, it worked for me locally but I'd like to be extra safe. Would be great if you could review this for me.

Launch demo link added to Homepage

---

hugo/content/docs/editing/data-files.md

Updated the documentation of data fields, based on the latest feature release.

Data File Documentation Updates

---

hugo/content/docs/settings/fields/datetime.md

Update datetime.md - fix duplicated content

---

hugo/content/docs/faqs/how-to-use-yaml-json-front-matter-w-hugo.md

Which apparently is the Hugo config.toml file.

Clarify context of what "config" file to use

---

hugo/content/docs/sunset/deployments.md

Warn existing users that the deployment feature Is ending at the end of 2019.

👋 Sunset notice for deployments

---

hugo/content/blog/creating-a-multilingual-blog-with-jekyll.md

Thanks for the article by the way !

Correct a typo in html content

---

hugo/content/job-application.md
hugo/content/job-openings/_index.md
hugo/content/job-openings/solutions-engineer.md

As a Hiring Manager
I can gather applications in HubSpot
Each application has its own form in HubSpot.

Add Hubspot job application form

---

hugo/content/docs/guides/developing-with-hugo/short-codes.md

No direct shortcodes, but snippets serve the purpose.

Snippets enable management of Hugo shortcodes

---

hugo/content/docs/guides/developing-with-hugo/project-structure.md

Hugo doesn't use the _ prefix to the data directory.

Hugo data files directory fix

---

hugo/content/docs/guides/developing-with-hugo/short-codes.md

Based on how they are used in Hugo documentation.

"shortcodes" is one word

---

hugo/content/docs/faqs/glossary/static-site-generators.md

Made a couple of quick fixes as listed in the PR name.

Added a missing space after NextJS and added 'to' before StaticGen link

---

hugo/content/docs/hosting.md

Sync was incorrectly written as "Synch"

Correct Typo

---

hugo/content/docs/settings/front-matter-templates.md

great product btw, love it so far

typo: dpcument => document

---

hugo/content/blog/announcing-tina-an-open-source-site-editor.md

I wasn't sure what you wanted after "Reach out" so I just guessed :)

Fix typo on the Tina announcement page

---

.github/workflows/config.yml

Updated env vars for non-master branches

Updated env vars for non-master branches

---

hugo/content/blog/creating-a-multilingual-blog-with-jekyll.md

Add closing quote to footer of multi-lingual page

---

hugo/content/docs/previews/build-commands.md

Fix small inconsistencies in command and text under
Customizing the Preview Command

Fix small inconsistencies in doc [build-commands.md]

---

hugo/content/docs/editing.md

fixed "toogle" to "toggle" in 3rd graf

fixed typo
