forestryio/forestry.io

hugo/content/blog/search-with-algolia-in-hugo.md
All I've done here is copy the code here: https://github.com/forestryio/forestry.io/blob/master/hugo/layouts/_default/list.algolia.json
to replace the previous version.
This fixes the data-race issues that will break website as listed here: https://github.com/gohugoio/hugo/issues/4557
I have not tested this code, but I'm pretty positive it works (it's also being used in the forestry codebase)
Side note: Thanks for this article, it was very helpful in setting up Algolia with Hugo!
=> Fixing Data Race Issues

hugo/content/blog/hugo-json-api-part-2.md
The URL changed could be changed to be consistent with the name used in other examples, but I didn't want to make an editorial change.
=> Fix small typos

hugo/layouts/blog/single.html
I noticed all author bios have a missing forward slash which causes an unnecessary redirect and probably a few milliseconds of time.
For example: My bio link on my posts is`https://forestry.io/authors/colin-garvey` which redirects to `https://forestry.io/authors/colin-garvey/`.
=> Fix Unnecessary Author Bio Link Redirect

hugo/content/blog/for-static-sites-theres-no-excuse-not-to-use-a-cdn.md
While the timing of the two pings have a relationship of the initial being 100% and the second being 600% of that value, The increase from the first to the second is ~498.40 %.  This is why I have changed from 600% to 500% -- to be more correct.
=> Change increase from 600% to 500%

hugo/layouts/partials/head.html
This snippet is added to reduce the risk of page flicker when running experiments with Google Optimize and Tag Manager.
I implemented them according to these best practices in snippet order 
👉 https://support.google.com/optimize/answer/7359264?hl=en
=> Hide page snippet

.circleci/config.yml, gulpfile.babel.js, package.json
We stumbled upon an issue a little while ago where, if you have non-draft content in branches other than master, CircleCI will still publish that content to the algolia search index when the commit builds. This can result in content appearing in search results that isn't actually available on the production site.
IMO, sending the search index to algolia is a pretty significant side effect for a script labeled "build". However, I realized that this action is dependent on the search index being built in the first place, so it does make sense to execute it at a specific point in the build process.
The solution I've come up with is to remove algolia from the `build` command and create a new `preDeploy` command that runs algolia after build. This makes it simple to run either/or depending on …
=> Change algolia dispatch

hugo/content/blog/how-to-use-hugo-s-image-processing-with-forestry.md
See Hugo docs: https://gohugo.io/content-management/page-bundles/#headless-bundle
"Only leaf bundles can be made headless."
GetPage and Resources.GetMatch work either way, but Hugo will render the section if `_index.md` is used rather than `index.md`, regardless of headless param.
=> correct documentation for usage of headless bundle

hugo/content/docs/media/cloudinary.md
Removed the trailing forward slash from `cloudinary_url` because the examples given below explicitly add a forward slash.
=> Remove trailing forward slash from cloudinary_url

hugo/config.toml
As discussed with @scottgallant, adding a link to our Product Board Roadmap in the footer.
=> Add link to Roadmap in footer

hugo/content/docs/faqs/forestry-changed-code.md
Newlines isn't a word and the title now matches the word in the paragraph it introduces.
=> Separated "new" and "lines" in title

hugo/content/docs/media/cloudinary.md
Minor typo replaced `int` with `into`
=> Minor typo in Cloudinary media docs

hugo/content/docs/hosting.md, hugo/content/docs/hosting/amazon-s3.md, hugo/content/docs/hosting/ftp.md, hugo/content/docs/hosting/github-pages.md, hugo/content/docs/hosting/s3-cloudfront-stack.md
Set expire date to January 2020, 1st.
=> Docs: add deprecation warning on hosting pages.

hugo/config.toml
What is the production cloudinary account?
Some images respond to forestry-demo, others to forestry-io.
=> Fix: Cloudinary name

hugo/content/docs/settings/fields/select.md
The example should now work as written.
=> Fix Jekyll data file and reference.

hugo/content/blog/write-better-javascript-with-webpack.md
Specifying
```
"build": "./node_modules/webpack-cli/bin/webpack.js"
```
in a `package.json` script is unnecessarily verbose. When you run a script, npm adds binaries from the local `node_modules/` to the `PATH`. Therefore, you can simply write
```
"build": "webpack"
```
=> Use bin name instead of relative path in scripts

hugo/content/blog/blocks-give-your-editors-the-power-to-build-pages.md, hugo/content/blog/sawmill-layout-composer-for-hugo-and-forestry.md
Sawmill repository has been transferred from dwalkr to forestryio so this PR is reflecting this change.
Related to: https://github.com/forestryio/sawmill/pull/5 and https://github.com/dwalkr/sawmill-starter/pull/1
=> Update the github repository name to forestryio

hugo/content/docs/previews/build-commands.md
update preview build command for Gridsome from `gridsome develop -H 0.0.0.0 -p 8080` to `gridsome develop -h 0.0.0.0 -p 8080`
When I tried running `gridsome develop -H 0.0.0.0 -p 8080` 
I got this error:
```bash
error: unknown option `-H'
```
I had to swap out the `-H` for `-h` before it worked.
=> Update Gridsome build command in build-commands.md

hugo/content/docs/guides/developing-with-hugo/templating.md
The previous documentation implied that files would be prefixed with .ace or .amber. 
This means the file would be `.ace.example` instead of `example.ace`
=> Clarify template file documentation

hugo/content/docs/settings/fields/textarea.md
The example configuration was missing the `schema.format` key.
Please double check that it is correct as I don't know if it's `snake case` (`inline_html`) or camelCase (`inlineHtml`).
This way it will be more clear on which formatting options are available
=> Textarea field: add the format configuration

hugo/content/docs/settings/fields/textarea.md
Based on [your comment](https://github.com/forestryio/forestry.io/pull/192#issuecomment-594483426) of #192 , I re-ordered the available values and also decided to be more explicit on the name/values pairs.
=> Update doc on textarea schema values

hugo/content/docs/faqs/front-matter-fallbacks.md
Replace "front matter in Hugo" with "front matter in Jekyll" where Jekyll defaults is the subject
=> Typo where is should say Jekyll

hugo/content/docs/guides/developing-with-hugo/environments.md
Deployment options are deprecated since January 31st, 2020.
=> Forestry doesn't deploy to production environments

hugo/content/blog/creating-a-multilingual-blog-with-jekyll.md
The current use of underscores corrupt the file name being displayed.
=> Fix underscore formatting issue

hugo/content/docs/troubleshooting/using-private-submodules.md
As title, I've added a space between `andcopy`.
Typo `andcopy`.
=> Add missing space to "using-pritvate-submodule" page

hugo/content/docs/previews/instant-previews.md
Relates to support request solved by @DirtyF. Gatsby starts on port 8000 by default, so specifying the port is required for previews.
> I see you were running Gatsby on default port 8000 and you're getting a 504 network error, our network layer do not seem to manage to redirect port 8000 to port 8080, it means you have to pass gatsby develop the port option to force running on 8080.
=> Add port number to Gatsby preview command

hugo/content/docs/guides/developing-with-hugo/asset-pipeline.md
In asset-pipeline.md, address a minor grammatical error.
=> Fix grammar error in developing-with-hugo

.github/workflows/config.yml
it appears that the gem install is failing due to
incomplete platform metadata, this is an attempt
to fix
=> setup ruby before installing htmlproofer gem
